-- local cmp = require'cmp'
-- cmp.setup({
--     snippet = {
--         expand = function(args)
--             vim.fn["UltiSnips#Anon"](args.body)
--         end,
--     },
--     window = {
--         completion = cmp.config.window.bordered(),
--         documentation = cmp.config.window.bordered()
--     },
--     mapping = cmp.mapping.preset.insert({
--         ['<C-b>'] = cmp.mapping.scroll_docs(-4),
--         ['<C-f>'] = cmp.mapping.scroll_docs(-4),
--         ['<C-Space>'] = cmp.mapping.complete(),
--         ['<C-e>'] = cmp.mapping.abort(),
--         ['<CR>'] = cmp.mapping.confirm({ select = true })
--     }),
--     sources = cmp.config.sources({
--         {
--             { name = 'nvim_lsp' },
--             { name = 'ultisnips' }
--         },
--         {
--             { name = 'buffer' }
--         }
--     })
-- })
-- cmp.setup.filetype('gitcommit', {
--     sources = cmp.config.sources({
--         { { name = 'cmp_git' } },
--         { { name = 'buffer' } }
--     })
-- })

-- doesn't work?
-- local vim.g.coq_settings = {
--     'auto_start': 'shut-up',
--     'keymap.jump_to_mark': '<C-n>'
-- }
local coq = require('coq')
